### ISSUE TITLE
Do not show hidden categories in rv-menutree

### ISSUE THREAD

**Issue by BenMak** [modus75/piwigo-menutree#1]
Currently RV-menutree also shows the categories which have in the namefield \'}
and before {/foreach} on line 15: {/if}

_{foreach from=$block->data.MENU_CATEGORIES item=cat}
        {$cat.PRE}
        **{if !$cat.NAME|stristr:'\\'}**
        <li{$cat.CLASS}> <a href="{$cat.URL}"{if $cat.IS_UPPERCAT} rel="up"{/if}>{$cat.NAME}</a>
                {if $cat.count_images > 0}
                        \<span{if $cat.nb_images <= 0} class=menuInfoCatByChild{/if} title="{$cat.TITLE}"\> [{$cat.count_images}] \</span\>
                {/if}
                {if !empty($cat.icon_ts)}
                        \<img title="{$cat.icon_ts.TITLE}" src="{$ROOT_URL}{$themeconf.icon_dir}/recent{if $cat.icon_ts.IS_CHILD_DATE}_by_child{/if}.png" alt="(!)"\>
                {/if}
        **{/if}**
{/foreach}_

**Comment by modus75** [comment]
That feature is part of another plug-in (not core). Your solution does not
work if you hide an album that has children which are not hidden.

However I will look into how to make this plug-in compatible with extended
description plugin.

**Comment by BenMak** [comment]
modus75,

Thanks for your fast action. Works well for me!

Regards,
Ben Makkink

2017-03-14 21:33 GMT+01:00 modus75 <notifications@github.com>:
